import { Event } from './types'

export const events: Event[] = [
  {
    id: '1',
    slug: 'nations-championship-2026-twickenham',
    title: 'Nations Championship 2026',
    subtitle: 'Twickenham Stadium',
    location: 'Twickenham, London',
    country: 'United Kingdom',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    date: 'March 2026',
    dateRange: '7–8 March 2026',
    price: 165,
    priceDisplay: '£165 pp',
    capacity: 300,
    spotsLeft: 47,
    featured: true,
    image: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1400&q=80',
    category: 'rugby',
    description:
      'The jewel in the crown of the Legends Series calendar. Join us at the home of English rugby for an unmissable afternoon of world-class international rugby, gourmet dining, and unprecedented access to the legends who made the game what it is today.',
    highlights: [
      'Private pre-match reception with rugby legends',
      'Premium 3-course gourmet dining',
      'Unrestricted open bar throughout',
      'Best seats in the stadium — Category 1',
      'Exclusive post-match legends Q&A session',
      'Personalised match programme & keepsake',
    ],
    legends: ['Lawrence Dallaglio', 'Martin Johnson', 'Jonny Wilkinson', 'Phil de Glanville'],
    included: [
      'Match ticket (Category 1)',
      'Pre-match hospitality reception',
      'Three-course lunch',
      'Post-match drinks',
      'Legends meet-and-greet',
    ],
  },
  {
    id: '2',
    slug: 'sa-rugby-experience-cape-town',
    title: 'SA Rugby Experience',
    subtitle: 'Cape Town Stadium',
    location: 'Cape Town',
    country: 'South Africa',
    flag: '🇿🇦',
    date: 'June 2026',
    dateRange: '12–16 June 2026',
    price: 4495,
    priceDisplay: '£4,495 pp',
    capacity: 50,
    spotsLeft: 12,
    featured: false,
    image: 'https://images.unsplash.com/photo-1544568100-847a948585b9?w=900&q=80',
    category: 'rugby',
    description:
      'A once-in-a-lifetime rugby safari: watch the Springboks in their spiritual home, dine at acclaimed Cape Winelands restaurants, and share a sundowner with living legends against the backdrop of Table Mountain.',
    highlights: [
      'International Test match with Category 1 seats',
      'Private training session access',
      'Exclusive Cape Winelands wine safari',
      'Table Mountain sunset sundowner with legends',
      'Five-star Camps Bay hotel, 4 nights',
    ],
    legends: ['Bryan Habana', 'Victor Matfield'],
    included: [
      'Return flights from London',
      'Airport transfers',
      'Four nights luxury accommodation',
      'All meals and activities listed',
    ],
  },
  {
    id: '3',
    slug: 'cresta-run-st-moritz',
    title: 'Cresta Run',
    subtitle: 'St. Moritz, Switzerland',
    location: 'St. Moritz',
    country: 'Switzerland',
    flag: '🇨🇭',
    date: 'January 2026',
    dateRange: '22–25 January 2026',
    price: 10000,
    priceDisplay: '£10,000 pp',
    capacity: 20,
    spotsLeft: 4,
    featured: false,
    image: 'https://images.unsplash.com/photo-1551524164-687a55dd1126?w=900&q=80',
    category: 'adventure',
    description:
      'The world\'s most exclusive toboggan run. Race down the legendary Cresta Run at 80mph alongside rugby\'s boldest characters, then unwind in the world\'s most glamorous alpine resort.',
    highlights: [
      'Full Cresta Run riding experience',
      'Professional coaching and safety briefing',
      'Four nights at Badrutt\'s Palace Hotel',
      'Private fondue evening with legends',
      'Helicopter transfer to resort',
    ],
    legends: ['Ben Cohen', 'Mike Catt'],
    included: [
      'Helicopter from Zurich',
      'Four nights at Badrutt\'s Palace',
      'All Cresta Run fees and equipment',
      'All meals and après-ski',
    ],
  },
  {
    id: '4',
    slug: 'orient-express-rugby-journey',
    title: 'Orient Express Journey',
    subtitle: 'Venice to Istanbul',
    location: 'Venice — Istanbul',
    country: 'Europe',
    flag: '🌍',
    date: 'October 2026',
    dateRange: '3–8 October 2026',
    price: 7500,
    priceDisplay: 'From £7,500',
    capacity: 30,
    spotsLeft: 9,
    featured: false,
    image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=900&q=80',
    category: 'luxury-travel',
    description:
      'Europe\'s most romantic journey reimagined. Board the Venice Simplon-Orient-Express with rugby\'s greatest storytellers for a five-night odyssey across the continent.',
    highlights: [
      'Five nights aboard the Orient-Express',
      'Private cabin with legend dining companions',
      'Exclusive cocktail receptions in the bar car',
      'Shore excursions in Verona and Zagreb',
      'Arriving in Istanbul for a Galatasaray fixture',
    ],
    legends: ['Clive Woodward', 'Lawrence Dallaglio'],
    included: [
      'All aboard the Orient-Express (5 nights)',
      'All meals and drinks on train',
      'Shore excursions',
      'Istanbul match ticket',
    ],
  },
  {
    id: '5',
    slug: 'bethpage-black-golf',
    title: 'Bethpage Black Golf',
    subtitle: 'Long Island, New York',
    location: 'Long Island, NY',
    country: 'United States',
    flag: '🇺🇸',
    date: 'May 2026',
    dateRange: '18–22 May 2026',
    price: 6800,
    priceDisplay: '£6,800 pp',
    capacity: 24,
    spotsLeft: 6,
    featured: false,
    image: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=900&q=80',
    category: 'golf',
    description:
      'Play the beast. Bethpage Black — site of multiple US Opens and widely considered the hardest public course in America — awaits. Tee up alongside rugby legends who\'ve found a new obsession.',
    highlights: [
      'Exclusive tee times on Bethpage Black',
      'Professional golf clinic with PGA Pro',
      'Three nights at The Garden City Hotel',
      'Yankee Stadium VIP box experience',
      'New York City evening hospitality',
    ],
    legends: ['Austin Healey', 'Ugo Monye'],
    included: [
      'Return flights from London',
      'Three nights luxury hotel',
      'All golf green fees and cart hire',
      'All meals and activities',
    ],
  },
  {
    id: '6',
    slug: 'golf-national-paris',
    title: 'Golf National Paris',
    subtitle: 'Ryder Cup Course',
    location: 'Paris, France',
    country: 'France',
    flag: '🇫🇷',
    date: 'September 2026',
    dateRange: '11–13 September 2026',
    price: 2200,
    priceDisplay: '£2,200 pp',
    capacity: 40,
    spotsLeft: 15,
    featured: false,
    image: 'https://images.unsplash.com/photo-1592919505780-303950717480?w=900&q=80',
    category: 'golf',
    description:
      'Tee up on the Albatros course — home of the 2018 Ryder Cup — for a long weekend in Paris that combines elite golf with the finest French dining.',
    highlights: [
      'Golf on the Ryder Cup Albatros course',
      'Two nights at Waldorf Astoria Versailles',
      'Michelin-starred dinner in Paris',
      'Legends golf clinic — play the same holes',
      'Eurostar travel from London included',
    ],
    legends: ['Jonny Wilkinson', 'Phil de Glanville'],
    included: [
      'Eurostar from London St Pancras',
      'Two nights Waldorf Astoria Versailles',
      'All golf and green fees',
      'Three-course dinner (Friday)',
    ],
  },
  {
    id: '7',
    slug: 'dubai-7s-hospitality',
    title: 'Dubai Sevens',
    subtitle: 'The Sevens Stadium, Dubai',
    location: 'Dubai',
    country: 'UAE',
    flag: '🇦🇪',
    date: 'December 2026',
    dateRange: '4–6 December 2026',
    price: 3200,
    priceDisplay: '£3,200 pp',
    capacity: 80,
    spotsLeft: 23,
    featured: false,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=900&q=80',
    category: 'rugby',
    description:
      'Dubai\'s most spectacular social event of the year. Three days of world sevens rugby, legendary parties, and unrivalled sunshine at one of sport\'s most iconic festivals.',
    highlights: [
      'Three-day hospitality suite with poolside views',
      'All-inclusive food and beverages',
      'Celebrity legends appearances each day',
      'Desert sunset safari and dinner',
      'Exclusive after-party with Legends Series crew',
    ],
    legends: ['Dan Luger', 'Ben Cohen'],
    included: [
      'Return flights from London',
      'Three nights at Atlantis The Palm',
      'Three-day hospitality suite passes',
      'All meals and premium drinks',
    ],
  },
]

export function getEventBySlug(slug: string): Event | undefined {
  return events.find((e) => e.slug === slug)
}

export function getFeaturedEvent(): Event {
  return events.find((e) => e.featured) ?? events[0]
}

export function getNonFeaturedEvents(): Event[] {
  return events.filter((e) => !e.featured)
}
