import { Legend } from './types'

export const legends: Legend[] = [
  // ── ENGLAND ──────────────────────────────────────────────────────────────
  {
    id: 'alex-goode',
    slug: 'alex-goode',
    name: 'Alex Goode',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens & England',
  },
  {
    id: 'alex-tait',
    slug: 'alex-tait',
    name: 'Alex Tait',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Newcastle & England',
  },
  {
    id: 'ben-foden',
    slug: 'ben-foden',
    name: 'Ben Foden',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Northampton Saints & England',
  },
  {
    id: 'ben-gollings',
    slug: 'ben-gollings',
    name: 'Ben Gollings',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Harlequins / Newcastle / England 7's",
  },
  {
    id: 'ben-woods',
    slug: 'ben-woods',
    name: 'Ben Woods',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Leicester / Cambridge / England 7's",
  },
  {
    id: 'brad-barritt',
    slug: 'brad-barritt',
    name: 'Brad Barritt',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens / England / Lions',
  },
  {
    id: 'dave-atwood',
    slug: 'dave-atwood',
    name: 'Dave Atwood',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / Toulon / England',
  },
  {
    id: 'dave-ewers',
    slug: 'dave-ewers',
    name: 'Dave Ewers',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Exeter / Stormers / England A',
  },
  {
    id: 'david-strettle',
    slug: 'david-strettle',
    name: 'David Strettle',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Harlequins / Saracens / England',
  },
  {
    id: 'delon-armitage',
    slug: 'delon-armitage',
    name: 'Delon Armitage',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'London Irish / Toulon / England',
  },
  {
    id: 'ed-williamson',
    slug: 'ed-williamson',
    name: 'Ed Williamson',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Newcastle / Leeds / RFC Libournais / England 7's",
  },
  {
    id: 'guy-thompson',
    slug: 'guy-thompson',
    name: 'Guy Thompson',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Wasps',
  },
  {
    id: 'iain-balshaw',
    slug: 'iain-balshaw',
    name: 'Iain Balshaw',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / Gloucester / England / Lions',
  },
  {
    id: 'jackson-wray',
    slug: 'jackson-wray',
    name: 'Jackson Wray',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens',
  },
  {
    id: 'james-buckland',
    slug: 'james-buckland',
    name: 'James Buckland',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester Tigers',
  },
  {
    id: 'james-smith',
    slug: 'james-smith',
    name: 'James Smith',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Gloucester',
  },
  {
    id: 'jason-hobson',
    slug: 'jason-hobson',
    name: 'Jason Hobson',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bristol / Wasps / Exeter / England',
  },
  {
    id: 'jon-phillips',
    slug: 'jon-phillips',
    name: 'Jon Phillips',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Northampton / Bedford',
  },
  {
    id: 'jonny-barrett',
    slug: 'jonny-barrett',
    name: 'Jonny Barrett',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Wasps',
  },
  {
    id: 'kai-hortsmann',
    slug: 'kai-hortsmann',
    name: 'Kai Hortsmann',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Harlequins / Worcester / Exeter / England 7's / Saxons",
  },
  {
    id: 'kevin-yates',
    slug: 'kevin-yates',
    name: 'Kevin Yates',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / Sale / Saracens / England',
  },
  {
    id: 'lee-dickson',
    slug: 'lee-dickson',
    name: 'Lee Dickson',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Newcastle / Northampton / England',
  },
  {
    id: 'lee-mears',
    slug: 'lee-mears',
    name: 'Lee Mears',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / England / Lions',
  },
  {
    id: 'leon-lloyd',
    slug: 'leon-lloyd',
    name: 'Leon Lloyd',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester & England',
  },
  {
    id: 'lewis-moody',
    slug: 'lewis-moody',
    name: 'Lewis Moody MBE',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester / Bath / England / Lions',
    caps: 71,
    achievements: [
      '2003 Rugby World Cup Winner',
      'British & Irish Lions 2005',
      '220+ appearances for Leicester Tigers',
      'England Captain',
    ],
    bio: "Affectionately nicknamed 'Mad Dog' for his all-action, fearless style of play, Lewis Moody MBE spent 14 seasons with Leicester Tigers, winning seven Premiership titles and two European Cups. He earned 71 caps for England, captained the side, and was a key member of the 2003 World Cup-winning squad.",
  },
  {
    id: 'luther-burrell',
    slug: 'luther-burrell',
    name: 'Luther Burrell',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Northampton / Newcastle / England',
  },
  {
    id: 'manu-tuilagi',
    slug: 'manu-tuilagi',
    name: 'Manu Tuilagi',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester / Sale / Bayonne / England / Lions',
  },
  {
    id: 'mark-regan',
    slug: 'mark-regan',
    name: 'Mark (Ronnie) Regan',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / Leeds / Bristol / England / Lions',
  },
  {
    id: 'matt-cornwell',
    slug: 'matt-cornwell',
    name: 'Matt Cornwell',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester / Northampton',
  },
  {
    id: 'matt-stevens',
    slug: 'matt-stevens',
    name: 'Matt Stevens',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / Saracens / Toulon / England / Lions',
  },
  {
    id: 'neil-clark',
    slug: 'neil-clark',
    name: 'Neil Clark',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bristol / Bath / Exeter / Oyonnax',
  },
  {
    id: 'ollie-phillips',
    slug: 'ollie-phillips',
    name: 'Ollie Phillips',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Newcastle / Gloucester / Stade Francais / England 7's",
  },
  {
    id: 'ollie-smith',
    slug: 'ollie-smith',
    name: 'Ollie Smith',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester / England / Lions',
  },
  {
    id: 'paul-doran-jones',
    slug: 'paul-doran-jones',
    name: 'Paul Doran-Jones',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Gloucester / Northampton / Harlequins',
  },
  {
    id: 'richard-barrington',
    slug: 'richard-barrington',
    name: 'Richard (Baz) Barrington',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens',
  },
  {
    id: 'richard-de-carpentier',
    slug: 'richard-de-carpentier',
    name: 'Richard de Carpentier',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Worcester / Bath / England 7's",
  },
  {
    id: 'rob-webber',
    slug: 'rob-webber',
    name: 'Rob Webber',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Wasps / Bath / Sale / England',
  },
  {
    id: 'steffon-armitage',
    slug: 'steffon-armitage',
    name: 'Steffon Armitage',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens / London Irish / Toulon / England',
  },
  {
    id: 'toby-flood',
    slug: 'toby-flood',
    name: 'Toby Flood',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester / Newcastle / England',
  },
  {
    id: 'tom-may',
    slug: 'tom-may',
    name: 'Tom May',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Newcastle / Toulon / Northampton / England',
  },
  {
    id: 'tyson-lewis',
    slug: 'tyson-lewis',
    name: 'Tyson Lewis',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Plymouth Albion / Doncaster Knights',
  },

  // ── WALES ─────────────────────────────────────────────────────────────────
  {
    id: 'alex-cuthbert',
    slug: 'alex-cuthbert',
    name: 'Alex Cuthbert',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Cardiff / Exeter / Wales / Lions',
  },
  {
    id: 'andy-powell',
    slug: 'andy-powell',
    name: 'Andy Powell',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Wales / Lions',
  },
  {
    id: 'dom-day',
    slug: 'dom-day',
    name: 'Dom Day',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Scarlets / Bath / Saracens / Wales',
  },
  {
    id: 'ieuan-evans',
    slug: 'ieuan-evans',
    name: 'Ieuan Evans',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Llanelli / Bath / Wales / Lions',
  },
  {
    id: 'james-hook',
    slug: 'james-hook',
    name: 'James Hook',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Ospreys / Gloucester / Wales / Lions',
  },
  {
    id: 'jamie-roberts',
    slug: 'jamie-roberts',
    name: 'Jamie Roberts',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Cardiff / Racing / Harlequins / Bath / Wales / Lions',
  },
  {
    id: 'leigh-halfpenny',
    slug: 'leigh-halfpenny',
    name: 'Leigh Halfpenny',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Cardiff / Scarlets / Toulon / Wales / Lions',
  },
  {
    id: 'matt-jess',
    slug: 'matt-jess',
    name: 'Matt Jess',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Exeter / Gwent Dragons',
  },
  {
    id: 'mike-phillips',
    slug: 'mike-phillips',
    name: 'Mike Phillips',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Llanelli / Cardiff / Ospreys / Racing / Wales / Lions',
  },
  {
    id: 'rhys-gill',
    slug: 'rhys-gill',
    name: 'Rhys Gill',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Saracens / Cardiff / Wales',
  },
  {
    id: 'rhys-priestland',
    slug: 'rhys-priestland',
    name: 'Rhys Priestland',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Scarlets / Bath / Wales',
  },
  {
    id: 'shane-williams',
    slug: 'shane-williams',
    name: 'Shane Williams',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Neath / Ospreys / Mitsubishi / Wales / Lions',
  },

  // ── IRELAND ───────────────────────────────────────────────────────────────
  {
    id: 'craig-gilroy',
    slug: 'craig-gilroy',
    name: 'Craig Gilroy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Ulster / Ireland',
  },
  {
    id: 'dan-leavy',
    slug: 'dan-leavy',
    name: 'Dan Leavy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland',
  },
  {
    id: 'dan-tuohy',
    slug: 'dan-tuohy',
    name: 'Dan Tuohy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Exeter / Ulster / Ireland',
  },
  {
    id: 'devin-toner',
    slug: 'devin-toner',
    name: 'Devin Toner',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland',
  },
  {
    id: 'fionn-carr',
    slug: 'fionn-carr',
    name: 'Fionn Carr',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: "Leinster / Connacht / Ireland 7's",
  },
  {
    id: 'gareth-steenson',
    slug: 'gareth-steenson',
    name: 'Gareth Steenson',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: "Exeter / Ireland 21's",
  },
  {
    id: 'geordan-murphy',
    slug: 'geordan-murphy',
    name: 'Geordan Murphy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leicester / Ireland / Lions',
  },
  {
    id: 'harry-mcnulty',
    slug: 'harry-mcnulty',
    name: 'Harry McNulty',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: "LA Giltinis / Ireland 7's",
  },
  {
    id: 'jack-mcgrath',
    slug: 'jack-mcgrath',
    name: 'Jack McGrath',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland / Lions',
  },
  {
    id: 'jamie-hagan',
    slug: 'jamie-hagan',
    name: 'Jamie Hagan',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Melbourne / La Rochelle / Ireland',
  },
  {
    id: 'jordi-conroy',
    slug: 'jordi-conroy',
    name: 'Jordi Conroy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: "Connacht / Delhi / Ireland 7's",
  },
  {
    id: 'jordi-murphy',
    slug: 'jordi-murphy',
    name: 'Jordi Murphy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ulster / Ireland',
  },
  {
    id: 'mick-kearney',
    slug: 'mick-kearney',
    name: 'Mick Kearney',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Connacht / Leinster / Zebre / Munster',
  },
  {
    id: 'mike-mccarthy',
    slug: 'mike-mccarthy',
    name: 'Mike McCarthy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Newcastle / Ireland',
  },
  {
    id: 'mike-ross',
    slug: 'mike-ross',
    name: 'Mike Ross',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland',
  },
  {
    id: 'paddy-wallace',
    slug: 'paddy-wallace',
    name: 'Paddy Wallace',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Ulster / Ireland',
  },
  {
    id: 'paul-marshall',
    slug: 'paul-marshall',
    name: 'Paul Marshall',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: "Ulster / Ireland 7's / Ireland",
  },
  {
    id: 'rob-henderson',
    slug: 'rob-henderson',
    name: 'Rob Henderson',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Wasps / Munster / Leinster / Toulon / Ireland / Lions',
  },
  {
    id: 'sean-obrien',
    slug: 'sean-obrien',
    name: "Sean O'Brien",
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland / Lions',
  },
  {
    id: 'shane-byrne',
    slug: 'shane-byrne',
    name: 'Shane Byrne',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland / Lions',
  },
  {
    id: 'tom-court',
    slug: 'tom-court',
    name: 'Tom Court',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland / Lions',
  },
  {
    id: 'tommy-bowe',
    slug: 'tommy-bowe',
    name: 'Tommy Bowe',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Ulster / Ospreys / Ireland / Lions',
  },

  // ── SCOTLAND ──────────────────────────────────────────────────────────────
  {
    id: 'craig-chalmers',
    slug: 'craig-chalmers',
    name: 'Craig Chalmers',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Edinburgh / Glasgow / Harlequins / Scotland / Lions',
  },
  {
    id: 'duncan-taylor',
    slug: 'duncan-taylor',
    name: 'Duncan Taylor',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Saracens / Scotland',
  },
  {
    id: 'kelly-brown',
    slug: 'kelly-brown',
    name: 'Kelly Brown',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Glasgow / Saracens / Scotland',
  },
  {
    id: 'ollie-atkins',
    slug: 'ollie-atkins',
    name: 'Ollie Atkins',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Edinburgh / Exeter',
  },
  {
    id: 'rory-lawson',
    slug: 'rory-lawson',
    name: 'Rory Lawson',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Edinburgh / Gloucester / Scotland',
  },
  {
    id: 'ryan-wilson',
    slug: 'ryan-wilson',
    name: 'Ryan Wilson',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Glasgow / Scotland',
  },
  {
    id: 'scott-steele',
    slug: 'scott-steele',
    name: 'Scott Steele',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Leicester / London Irish / Harlequins / Glasgow / Scotland',
  },
  {
    id: 'sean-lamont',
    slug: 'sean-lamont',
    name: 'Sean Lamont',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Glasgow / Northampton / Scotland',
  },
  {
    id: 'sean-maitland',
    slug: 'sean-maitland',
    name: 'Sean Maitland',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Glasgow / Saracens / Scotland / Lions',
  },
  {
    id: 'tommy-seymour',
    slug: 'tommy-seymour',
    name: 'Tommy Seymour',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Glasgow / Scotland / Lions',
  },

  // ── SOUTH AFRICA ──────────────────────────────────────────────────────────
  {
    id: 'schalk-brits',
    slug: 'schalk-brits',
    name: 'Schalk Brits',
    country: 'South Africa',
    flag: '🇿🇦',
    clubs: 'Saracens / South Africa',
  },

  // ── AUSTRALIA ─────────────────────────────────────────────────────────────
  {
    id: 'henry-speight',
    slug: 'henry-speight',
    name: 'Henry Speight',
    country: 'Australia',
    flag: '🇦🇺',
    clubs: 'Brumbies / Ulster / Queensland Reds / Biarritz / Australia',
  },
  {
    id: 'petrus-du-plessis',
    slug: 'petrus-du-plessis',
    name: 'Petrus (Parra) du Plessis',
    country: 'Australia',
    flag: '🇦🇺',
    clubs: 'Saracens / London Irish / Australia coaching',
  },

  // ── USA ───────────────────────────────────────────────────────────────────
  {
    id: 'sean-mcnulty',
    slug: 'sean-mcnulty',
    name: 'Sean McNulty',
    country: 'USA',
    flag: '🇺🇸',
    clubs: 'LA Gilitinis / Miami Sharks / USA Eagles',
  },

  // ── SPECIAL ROLES ─────────────────────────────────────────────────────────
  {
    id: 'christophe-ridley',
    slug: 'christophe-ridley',
    name: 'Christophe Ridley',
    country: 'Referee',
    flag: '🏉',
    clubs: 'IRB Referee',
    homeLocation: 'Cheltenham',
  },
  {
    id: 'rob-shotton',
    slug: 'rob-shotton',
    name: 'Rob Shotton',
    country: 'LooseHeadz',
    flag: '💚',
    clubs: 'Co-Founder LooseHeadz',
    homeLocation: 'London',
  },
  {
    id: 'sarah-webb',
    slug: 'sarah-webb',
    name: 'Sarah Webb',
    country: 'Wooden Spoon',
    flag: '🥄',
    clubs: 'CEO Wooden Spoon',
    homeLocation: 'Southampton',
  },
]

export const COUNTRY_ORDER = [
  'England',
  'Wales',
  'Ireland',
  'Scotland',
  'South Africa',
  'Australia',
  'USA',
  'Referee',
  'LooseHeadz',
  'Wooden Spoon',
]

export const legendsByCountry = COUNTRY_ORDER.reduce<Record<string, Legend[]>>(
  (acc, country) => {
    const group = legends.filter((l) => l.country === country)
    if (group.length > 0) acc[country] = group
    return acc
  },
  {}
)
