import { Legend } from './types'

export const legends: Legend[] = [
  {
    id: '1',
    slug: 'lawrence-dallaglio',
    name: 'Lawrence Dallaglio',
    position: 'Number 8',
    caps: 85,
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    achievements: [
      '2003 Rugby World Cup Winner',
      'British & Irish Lions 1997',
      '3× Premiership Champion',
      'Wasps Rugby Club Captain',
    ],
    bio: 'England\'s most decorated Number 8 and one of the defining figures of the professional era. Lawrence led England to World Cup glory in 2003 and captained his club Wasps to multiple Premiership titles. A fearless competitor on the field and a warm, magnetic presence off it — Lawrence is the heart and soul of the Legends Series experience.',
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
  },
  {
    id: '2',
    slug: 'martin-johnson',
    name: 'Martin Johnson',
    position: 'Lock',
    caps: 84,
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    achievements: [
      '2003 Rugby World Cup Winner & Captain',
      'British & Irish Lions Captain 1997 & 2001',
      '4× Premiership Champion with Leicester',
      'World Rugby Player of the Year 1993',
    ],
    bio: 'Quite simply the greatest captain in the history of English rugby. Martin Johnson led England to their historic 2003 World Cup win in Sydney — a result that defined a generation. His presence at any Legends Series event commands instant respect; guests routinely describe meeting Martin as a life-defining moment.',
    image: 'https://images.unsplash.com/photo-1546961342-ea5f62d5a27b?w=600&q=80',
  },
  {
    id: '3',
    slug: 'jonny-wilkinson',
    name: 'Jonny Wilkinson',
    position: 'Fly-Half',
    caps: 91,
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    achievements: [
      '2003 Rugby World Cup Winner',
      'Two-time Six Nations Grand Slam',
      'British & Irish Lions 2001',
      'Top scorer in World Cup history at the time',
    ],
    bio: 'The man who kicked the drop goal heard around the world. Jonny Wilkinson\'s 77-metre drop goal in extra time of the 2003 World Cup Final remains one of sport\'s most electric moments. A perfectionist, a gentleman, and one of the most sought-after guests at any Legends Series event.',
    image: 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=600&q=80',
  },
  {
    id: '4',
    slug: 'bryan-habana',
    name: 'Bryan Habana',
    position: 'Wing',
    caps: 124,
    country: 'South Africa',
    flag: '🇿🇦',
    achievements: [
      '2007 Rugby World Cup Winner',
      'World Rugby Player of the Year 2007',
      'Joint World Cup top try-scorer',
      '67 international tries',
    ],
    bio: 'Bryan Habana is the fastest man ever to play Test rugby — a player whose sheer explosive pace redefined what a wing could be. His 8 tries at the 2007 World Cup equalled Jonah Lomu\'s record. Still electrifying company at every Legends Series event he graces.',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
  },
  {
    id: '5',
    slug: 'victor-matfield',
    name: 'Victor Matfield',
    position: 'Lock',
    caps: 127,
    country: 'South Africa',
    flag: '🇿🇦',
    achievements: [
      '2007 & 2019 Rugby World Cup Winner',
      'World Rugby Player of the Year 2006',
      '3× Super Rugby titles',
      'Most capped Springbok lock',
    ],
    bio: 'The most complete lock forward in history. Victor Matfield was the engine room of two World Cup winning Springbok sides and the master tactician at the lineout. Thoughtful, insightful, and disarmingly funny — Victor is a guests\' favourite at every Legends Series event.',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80',
  },
  {
    id: '6',
    slug: 'ben-cohen',
    name: 'Ben Cohen',
    position: 'Wing',
    caps: 57,
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    achievements: [
      '2003 Rugby World Cup Winner',
      'Six Nations Grand Slam 2003',
      'Premiership Champion with Northampton',
      'IRB World XV',
    ],
    bio: 'One of the most explosive finishers of his generation, Ben Cohen was a key member of England\'s 2003 World Cup winning squad. Away from the pitch, Ben is one of the warmest, most entertaining presences at any Legends Series event — renowned for his storytelling and his love of a good party.',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&q=80',
  },
  {
    id: '7',
    slug: 'ugo-monye',
    name: 'Ugo Monye',
    position: 'Wing',
    caps: 21,
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    achievements: [
      'British & Irish Lions 2009',
      'Six Nations Grand Slam 2011',
      'Harlequins & England International',
      'BBC Sport rugby pundit',
    ],
    bio: 'One of the most recognisable faces in British rugby — both for his blistering performances on the wing and his brilliant media career. Ugo brings an infectious energy and insight to every Legends Series event and is consistently rated by guests as the highlight of their experience.',
    image: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&q=80',
  },
  {
    id: '8',
    slug: 'austin-healey',
    name: 'Austin Healey',
    position: 'Utility Back',
    caps: 51,
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    achievements: [
      '2003 Rugby World Cup Winner',
      'British & Irish Lions 1997 & 2001',
      'Six Nations Grand Slam 2003',
      'Premiership winner with Leicester',
    ],
    bio: 'The self-proclaimed "Guru" — Austin Healey is rugby\'s natural entertainer. Quick on the field, quicker with a one-liner off it. Austin\'s irreverence and wit made him one of rugby\'s most beloved characters, and those qualities make him the life and soul of every Legends Series gathering.',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&q=80',
  },
]
