import { Legend } from './types'

export const legends: Legend[] = [
  // ── ENGLAND ──────────────────────────────────────────────────────────────
  {
    id: 'alex-goode',
    slug: 'alex-goode',
    name: 'Alex Goode',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens & England',
    stat: 'One Club man at Saracens, multiple trophies, fan\'s favourite and wore his match kit (including gum shield) for 3 days straight after winning the Champions Cup Final',
  },
  {
    id: 'alex-tait',
    slug: 'alex-tait',
    name: 'Alex Tait',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Newcastle & England',
    stat: 'One-club man — spent his entire career at Newcastle Falcons',
  },
  {
    id: 'andy-goode',
    slug: 'andy-goode',
    name: 'Andy Goode',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester Tigers, Saracens, Worcester Warriors, Wasps, Newcastle Falcons, Brive (France), Sharks (South Africa) & England',
    stat: 'A beloved cult hero of English rugby, he sits as the second-highest point scorer in Premiership history and famously came out of retirement for a brief stint at Newcastle Falcons, scoring 16 points on his home debut',
  },
  {
    id: 'ben-foden',
    slug: 'ben-foden',
    name: 'Ben Foden',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Sale Sharks, Northampton Saints & England',
    stat: 'He earned the lifelong squad nickname "Pop Idol" (or "Pops") during his early days at Sale Sharks because he missed the first day of pre-season training to audition for Pop Idol. Made the Semi Finals of Celebrity X Factor with the boy band, Try Star',
  },
  {
    id: 'ben-gollings',
    slug: 'ben-gollings',
    name: 'Ben Gollings',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Harlequins / Newcastle / England 7's",
    stat: 'All-time leading World Sevens Series try scorer with 230 tries — a record that stood for over a decade',
  },
  {
    id: 'ben-woods',
    slug: 'ben-woods',
    name: 'Ben Woods',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Leicester / Cambridge / England 7's",
    stat: 'Combined a pro rugby career with studying at Cambridge University',
  },
  {
    id: 'charlie-hodgson',
    slug: 'charlie-hodgson',
    name: 'Charlie Hodgson',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Sale, Saracens & England',
    stat: 'He remains the all-time leading point scorer in Premiership Rugby history, having racked up an astonishing 2,525 points over his brilliant career!',
  },
  {
    id: 'brad-barritt',
    slug: 'brad-barritt',
    name: 'Brad Barritt',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens / England / Lions',
    stat: '26 caps for England. South African-born, captained Saracens to three Premiership titles',
  },
  {
    id: 'damian-hopley',
    slug: 'damian-hopley',
    name: 'Damian Hopley',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Wasps & England',
    stat: 'After a lightning-fast playing career cut short by injury, he went on to transform the game off the pitch by founding the Rugby Players Association (RPA) to champion player welfare',
  },
  {
    id: 'dave-atwood',
    slug: 'dave-atwood',
    name: 'Dave Atwood',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / Toulon / England',
    stat: '21 caps for England. Moved to Toulon and learned fluent French within a year',
  },
  {
    id: 'dave-ewers',
    slug: 'dave-ewers',
    name: 'Dave Ewers',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Exeter / Stormers / England A',
    stat: 'Zimbabwe-born powerhouse. Key part of Exeter\'s rise from the Championship to Premiership champions',
  },
  {
    id: 'david-strettle',
    slug: 'david-strettle',
    name: 'David Strettle',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Harlequins / Saracens / England',
    stat: '14 caps for England. Scored a Champions Cup final try for Saracens at age 35',
  },
  {
    id: 'delon-armitage',
    slug: 'delon-armitage',
    name: 'Delon Armitage',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'London Irish, Toulon & England',
    stat: '26 caps for England. Won the European Champions Cup with Toulon — twice. A fan\'s favourite and a live-wire on and off the pitch',
  },
  {
    id: 'george-chuter',
    slug: 'george-chuter',
    name: 'George Chuter',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens, Leicester & England',
    stat: 'Famous for his sharp wit off the pitch, he made history in 2007 by becoming the first player to feature in a Premiership, Heineken Cup, and World Cup final in the very same season',
  },
  {
    id: 'gregg-botterman',
    slug: 'gregg-botterman',
    name: 'Gregg Botterman',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens, Barbarians, Old Albanian & England A',
    stat: 'A beloved Saracens legend and front-row stalwart, he was as well known for his iconic dark hair and huge heart on the pitch as he was for bringing endless good humour to the club house',
  },
  {
    id: 'ed-williamson',
    slug: 'ed-williamson',
    name: 'Ed Williamson',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Newcastle Falcons, Leeds Carnegie, UA Libournaies & England 7's",
    stat: 'Both prior to and after his professional rugby career, he was a gifted artist — his work was exhibited at the Tate Modern while he was still at school. His work is now exhibited at prestigious galleries all over the world',
  },
  {
    id: 'guy-thompson',
    slug: 'guy-thompson',
    name: 'Guy Thompson',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Wasps',
    stat: '150+ appearances for Wasps. Won the Premiership Players\' Player of the Year',
  },
  {
    id: 'iain-balshaw',
    slug: 'iain-balshaw',
    name: 'Iain Balshaw',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / Gloucester / England / Lions',
    stat: '2003 World Cup winner. His electric running at fullback terrified defences during the 2001 Six Nations',
  },
  {
    id: 'jackson-wray',
    slug: 'jackson-wray',
    name: 'Jackson Wray',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens',
    stat: '300+ appearances for Saracens — one of the most capped players in the club\'s history',
  },
  {
    id: 'james-buckland',
    slug: 'james-buckland',
    name: 'James Buckland',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester Tigers',
    stat: 'Part of the Leicester Tigers dynasty during their back-to-back Premiership years',
  },
  {
    id: 'james-smith',
    slug: 'james-smith',
    name: 'James Smith',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Gloucester',
    stat: 'Following his professional rugby career with over 4 million online followers, he has become one of the world\'s most popular fitness influencers',
  },
  {
    id: 'jason-hobson',
    slug: 'jason-hobson',
    name: 'Jason Hobson',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bristol / Wasps / Exeter / England',
    stat: 'Played for four Premiership clubs — scrummaged his way around the West Country and beyond',
  },
  {
    id: 'jon-phillips',
    slug: 'jon-phillips',
    name: 'Jon Phillips',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Northampton / Bedford',
    stat: 'Part of the Northampton squad during the Saints\' Heineken Cup glory days',
  },
  {
    id: 'jonny-barrett',
    slug: 'jonny-barrett',
    name: 'Jonny Barrett',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Wasps',
    stat: 'Wasps through and through — loyal servant during their golden era at Adams Park and a fantastic tourist. Can sing a bit as well',
  },
  {
    id: 'kai-hortsmann',
    slug: 'kai-hortsmann',
    name: 'Kai Hortsmann',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Harlequins / Worcester / Exeter / England 7's / Saxons",
    stat: 'German-born flanker who represented England Saxons and played Sevens — a true rugby journeyman',
  },
  {
    id: 'kevin-yates',
    slug: 'kevin-yates',
    name: 'Kevin Yates',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / Sale / Saracens / England',
    stat: '4 caps for England. One of the most feared scrummagers in Premiership history',
  },
  {
    id: 'lee-dickson',
    slug: 'lee-dickson',
    name: 'Lee Dickson',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Newcastle / Northampton / England',
    stat: '18 caps for England. Known as one of the quickest scrum-halves off the ruck in English rugby',
  },
  {
    id: 'lee-mears',
    slug: 'lee-mears',
    name: 'Lee Mears',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / England / Lions',
    stat: '42 caps for England. Lions tourist in 2009. Retired to become a firefighter',
  },
  {
    id: 'leon-lloyd',
    slug: 'leon-lloyd',
    name: 'Leon Lloyd',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester & England',
    stat: 'Scored the winning try in the 2001 Heineken Cup final — one of Leicester\'s most iconic moments',
  },
  {
    id: 'lewis-moody',
    slug: 'lewis-moody',
    name: 'Lewis Moody MBE',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester / Bath / England / Lions',
    stat: '2003 World Cup winner. Nicknamed "Mad Dog" — once played an entire half with blood pouring from a head wound and refused to come off',
    achievements: [
      '2003 Rugby World Cup Winner',
      'British & Irish Lions 2005',
      '220+ appearances for Leicester Tigers',
      'England Captain',
    ],
    bio: "Affectionately nicknamed 'Mad Dog' for his all-action, fearless style of play, Lewis Moody MBE spent 14 seasons with Leicester Tigers, winning seven Premiership titles and two European Cups. He earned 71 caps for England, captained the side, and was a key member of the 2003 World Cup-winning squad.",
  },
  {
    id: 'luther-burrell',
    slug: 'luther-burrell',
    name: 'Luther Burrell',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Northampton / Newcastle / England',
    stat: '15 caps for England. Switched to professional boxing after retiring from rugby',
  },
  {
    id: 'manu-tuilagi',
    slug: 'manu-tuilagi',
    name: 'Manu Tuilagi',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester / Sale / Bayonne / England / Lions',
    stat: '50+ caps for England. Once jumped off a ferry into Auckland Harbour for a dare on the 2011 World Cup tour',
  },
  {
    id: 'mark-regan',
    slug: 'mark-regan',
    name: 'Mark (Ronnie) Regan',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / Leeds / Bristol / England / Lions',
    stat: '46 caps for England. Known as "Ronnie" — famous for his wind-ups and one of the great characters of English rugby',
  },
  {
    id: 'mike-tindall',
    slug: 'mike-tindall',
    name: 'Mike Tindall',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath, Gloucester & England',
    stat: 'Beyond winning the 2003 Rugby World Cup with England, he married Zara Phillips to join the royal family, eventually becoming the first royal in-law to swing through the jungle on I\'m a Celebrity... Get Me Out of Here!',
  },
  {
    id: 'matt-cornwell',
    slug: 'matt-cornwell',
    name: 'Matt Cornwell',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester / Northampton',
    stat: 'Played in the East Midlands derby for both sides — one of few to cross the Leicester-Northampton divide',
  },
  {
    id: 'matt-stevens',
    slug: 'matt-stevens',
    name: 'Matt Stevens',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bath / Saracens / Toulon / England / Lions',
    stat: '44 caps for England. Also a talented DJ — has played sets at clubs across Europe',
  },
  {
    id: 'neil-clark',
    slug: 'neil-clark',
    name: 'Neil Clark',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Bristol / Bath / Exeter / Oyonnax',
    stat: 'Played in France\'s Pro D2 with Oyonnax — embraced the full French rugby experience',
  },
  {
    id: 'ollie-phillips',
    slug: 'ollie-phillips',
    name: 'Ollie Phillips',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Newcastle / Gloucester / Stade Francais / England 7's",
    stat: 'IRB Sevens Player of the Year. Became a successful businessman and leadership speaker after rugby',
  },
  {
    id: 'ollie-smith',
    slug: 'ollie-smith',
    name: 'Ollie Smith',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester / England / Lions',
    stat: 'The only player in history to have scored more points for the British & Irish Lions than for his own country',
  },
  {
    id: 'paul-doran-jones',
    slug: 'paul-doran-jones',
    name: 'Paul Doran-Jones',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Gloucester / Northampton / Harlequins',
    stat: '200+ Premiership appearances across three clubs — a proper front-row warrior',
  },
  {
    id: 'rory-jenkins',
    slug: 'rory-jenkins',
    name: 'Rory Jenkins',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Harlequins & England A (Capt)',
    stat: 'Selected to play the All Blacks at Twickenham at the expense of Lawrence Dallaglio. A triple Cambridge Blue (Rugby, Cricket and Discus), after rugby Rory has gone on to a very successful legal career in the City',
  },
  {
    id: 'richard-barrington',
    slug: 'richard-barrington',
    name: 'Richard (Baz) Barrington',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens',
    stat: 'Part of the Saracens pack that dominated English and European rugby for a decade',
  },
  {
    id: 'richard-de-carpentier',
    slug: 'richard-de-carpentier',
    name: 'Richard de Carpentier',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: "Worcester / Bath / England 7's",
    stat: 'Represented England in Sevens — one of the most athletic forwards on the circuit',
  },
  {
    id: 'rob-webber',
    slug: 'rob-webber',
    name: 'Rob Webber',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Wasps / Bath / Sale / England',
    stat: '10 caps for England. Known for his thunderous carries from hooker — not your typical No. 2',
  },
  {
    id: 'steffon-armitage',
    slug: 'steffon-armitage',
    name: 'Steffon Armitage',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Saracens / London Irish / Toulon / England',
    stat: '5 caps for England. Won European Player of the Year at Toulon but was famously blocked from England selection while playing in France',
  },
  {
    id: 'toby-flood',
    slug: 'toby-flood',
    name: 'Toby Flood',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Leicester / Newcastle / England',
    stat: '60 caps for England. Scored over 300 points in international rugby',
  },
  {
    id: 'tom-may',
    slug: 'tom-may',
    name: 'Tom May',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Newcastle / Toulon / Northampton / England',
    stat: '5 caps for England. Won the Premiership with Northampton and the French title with Toulon in the same decade',
  },
  {
    id: 'tyson-lewis',
    slug: 'tyson-lewis',
    name: 'Tyson Lewis',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Plymouth Albion / Doncaster Knights',
    stat: 'Championship rugby stalwart — the heartbeat of the lower leagues where the passion runs just as deep',
  },

  // ── WALES ─────────────────────────────────────────────────────────────────
  {
    id: 'alex-cuthbert',
    slug: 'alex-cuthbert',
    name: 'Alex Cuthbert',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Cardiff / Exeter / Wales / Lions',
    stat: '48 caps for Wales. Scored two tries in the 2013 Six Nations win over England that denied them the Grand Slam',
  },
  {
    id: 'andy-powell',
    slug: 'andy-powell',
    name: 'Andy Powell',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Wales / Lions',
    stat: '23 caps for Wales. Drove a golf buggy down the M4 at 4am after a Six Nations win — arrested in his Wales tracksuit',
  },
  {
    id: 'dan-biggar',
    slug: 'dan-biggar',
    name: 'Dan Biggar',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Ospreys, Northampton Saints, Wales & British & Irish Lions',
    stat: 'The fiery Welsh fly-half\'s iconic, fidgety pre-kick routine at the 2015 Rugby World Cup became an instant internet sensation, affectionately dubbed by fans as the "Biggarena"! Now a knowledgeable pundit and podcast Superstar',
  },
  {
    id: 'dom-day',
    slug: 'dom-day',
    name: 'Dom Day',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Scarlets / Bath / Saracens / Wales',
    stat: '7 caps for Wales. Won three Premiership titles with Saracens as a key lineout operator',
  },
  {
    id: 'ieuan-evans',
    slug: 'ieuan-evans',
    name: 'Ieuan Evans',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Llanelli / Bath / Wales / Lions',
    stat: '72 caps for Wales. Scored THAT try against Scotland in 1988 — one of the most famous in Welsh rugby history',
  },
  {
    id: 'james-hook',
    slug: 'james-hook',
    name: 'James Hook',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Ospreys / Gloucester / Wales / Lions',
    stat: '81 caps for Wales. Could play fly-half, centre, or fullback — one of the most versatile players Wales has ever produced',
  },
  {
    id: 'jamie-roberts',
    slug: 'jamie-roberts',
    name: 'Jamie Roberts',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Cardiff / Racing / Harlequins / Bath / Wales / Lions',
    stat: '97 caps for Wales. Qualified as a medical doctor while playing international rugby — Dr Roberts to you',
  },
  {
    id: 'leigh-halfpenny',
    slug: 'leigh-halfpenny',
    name: 'Leigh Halfpenny',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Cardiff / Scarlets / Toulon / Wales / Lions',
    stat: '101 caps for Wales. 2013 Lions Player of the Series. Once kicked 20 consecutive goals in a Test series',
  },
  {
    id: 'matt-jess',
    slug: 'matt-jess',
    name: 'Matt Jess',
    country: 'England',
    flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    clubs: 'Exeter / Gwent Dragons',
    stat: 'Part of the Exeter squad that won promotion to the Premiership and never looked back',
  },
  {
    id: 'mike-phillips',
    slug: 'mike-phillips',
    name: 'Mike Phillips',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Llanelli / Cardiff / Ospreys / Racing / Wales / Lions',
    stat: '94 caps for Wales. 3 Lions tours. Famously confident — once told the All Blacks they were in for a long night',
  },
  {
    id: 'rhys-gill',
    slug: 'rhys-gill',
    name: 'Rhys Gill',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Saracens / Cardiff / Wales',
    stat: '7 caps for Wales. Won multiple Premiership titles scrummaging in the Saracens front row',
  },
  {
    id: 'rhys-priestland',
    slug: 'rhys-priestland',
    name: 'Rhys Priestland',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Scarlets / Bath / Wales',
    stat: '50 caps for Wales. Started the 2011 World Cup semi-final — one of Wales\' greatest tournament runs',
  },
  {
    id: 'shane-williams',
    slug: 'shane-williams',
    name: 'Shane Williams',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Neath / Ospreys / Mitsubishi / Wales / Lions',
    stat: '87 caps, 58 tries for Wales. IRB World Player of the Year 2008. Scored a try in his final Test — because of course he did',
  },

  {
    id: 'sam-warburton',
    slug: 'sam-warburton',
    name: 'Sam Warburton',
    country: 'Wales',
    flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    clubs: 'Cardiff, Wales & British & Irish Lions',
    stat: 'Before he became the youngest ever Welsh Captain, he played football with Gareth Bale. Captained two Lions tours, an immense leader of men',
  },

  // ── IRELAND ───────────────────────────────────────────────────────────────
  {
    id: 'craig-gilroy',
    slug: 'craig-gilroy',
    name: 'Craig Gilroy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Ulster / Ireland',
    stat: '9 caps for Ireland. Scored a try on his Ireland debut aged 21 — announced himself in style',
  },
  {
    id: 'dan-leavy',
    slug: 'dan-leavy',
    name: 'Dan Leavy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland',
    stat: '11 caps for Ireland. Was being tipped as world\'s best openside before a devastating knee injury cut him down',
  },
  {
    id: 'dan-tuohy',
    slug: 'dan-tuohy',
    name: 'Dan Tuohy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Exeter / Ulster / Ireland',
    stat: '11 caps for Ireland. A lineout specialist who could steal ball at will on his day',
  },
  {
    id: 'devin-toner',
    slug: 'devin-toner',
    name: 'Devin Toner',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland',
    stat: '70 caps for Ireland. At 6\'11" he\'s one of the tallest players ever to play international rugby',
  },
  {
    id: 'fionn-carr',
    slug: 'fionn-carr',
    name: 'Fionn Carr',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: "Leinster / Connacht / Ireland 7's",
    stat: 'Electric pace on the wing — one of the quickest players in Irish provincial rugby',
  },
  {
    id: 'gareth-steenson',
    slug: 'gareth-steenson',
    name: 'Gareth Steenson',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: "Exeter / Ireland 21's",
    stat: 'Kicked the penalty that won Exeter their first ever Premiership title in 2017. Club legend',
  },
  {
    id: 'geordan-murphy',
    slug: 'geordan-murphy',
    name: 'Geordan Murphy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leicester / Ireland / Lions',
    stat: '72 caps for Ireland. Spent 16 seasons at Leicester — the longest-serving overseas player in Tigers history',
  },
  {
    id: 'harry-mcnulty',
    slug: 'harry-mcnulty',
    name: 'Harry McNulty',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: "LA Giltinis / Ireland 7's",
    stat: 'Represented Ireland at the Olympics in Sevens — took Irish rugby to the world stage',
  },
  {
    id: 'jack-mcgrath',
    slug: 'jack-mcgrath',
    name: 'Jack McGrath',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland / Lions',
    stat: '54 caps for Ireland. Lions tourist 2017. A former boxer who brought that fighting spirit to the scrum',
  },
  {
    id: 'jamie-hagan',
    slug: 'jamie-hagan',
    name: 'Jamie Hagan',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Melbourne / La Rochelle / Ireland',
    stat: '3 caps for Ireland. Played club rugby across three countries — Ireland, Australia, and France',
  },
  {
    id: 'jordi-conroy',
    slug: 'jordi-conroy',
    name: 'Jordi Conroy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: "Connacht / Delhi / Ireland 7's",
    stat: 'Played Sevens for Ireland in Delhi — took the fast game from Connacht to the world circuit',
  },
  {
    id: 'jordi-murphy',
    slug: 'jordi-murphy',
    name: 'Jordi Murphy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ulster / Ireland',
    stat: '30 caps for Ireland. Called up mid-World Cup 2019 as injury cover and flew straight to Japan',
  },
  {
    id: 'mick-kearney',
    slug: 'mick-kearney',
    name: 'Mick Kearney',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Connacht / Leinster / Zebre / Munster',
    stat: 'Played for four Irish/Italian provinces — the ultimate journeyman of pro rugby',
  },
  {
    id: 'mike-mccarthy',
    slug: 'mike-mccarthy',
    name: 'Mike McCarthy',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Newcastle / Ireland',
    stat: '19 caps for Ireland. Once absolutely slaughtered a young Eben Etzebeth during Ireland vs South Africa in 2013',
  },
  {
    id: 'mike-ross',
    slug: 'mike-ross',
    name: 'Mike Ross',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland',
    stat: '61 caps for Ireland. Didn\'t win his first cap until he was 30 — proof it\'s never too late',
  },
  {
    id: 'paddy-wallace',
    slug: 'paddy-wallace',
    name: 'Paddy Wallace',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Ulster / Ireland',
    stat: '30 caps for Ireland. Could play centre or fly-half — Ulster\'s Mr Versatile',
  },
  {
    id: 'paul-marshall',
    slug: 'paul-marshall',
    name: 'Paul Marshall',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: "Ulster / Ireland 7's / Ireland",
    stat: '5 caps for Ireland. Made over 150 appearances for Ulster — the heartbeat of Ravenhill',
  },
  {
    id: 'rob-henderson',
    slug: 'rob-henderson',
    name: 'Rob Henderson',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Wasps / Munster / Leinster / Toulon / Ireland / Lions',
    stat: '19 caps for Ireland. Started the 2001 Lions first Test — held his own against the Wallabies in the midfield',
  },
  {
    id: 'sean-obrien',
    slug: 'sean-obrien',
    name: "Sean O'Brien",
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland / Lions',
    stat: '56 caps for Ireland. Tullow Tank. Scored the try that won the 2017 Lions first Test against New Zealand',
  },
  {
    id: 'shane-byrne',
    slug: 'shane-byrne',
    name: 'Shane Byrne',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland / Lions',
    stat: '41 caps for Ireland. Lions tourist 2005. A hooker with a sideline in property development',
  },
  {
    id: 'tom-court',
    slug: 'tom-court',
    name: 'Tom Court',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Leinster / Ireland / Lions',
    stat: '15 caps for Ireland. Australian-born prop who became a key part of the Ulster and Ireland pack',
  },
  {
    id: 'tommy-bowe',
    slug: 'tommy-bowe',
    name: 'Tommy Bowe',
    country: 'Ireland',
    flag: '🇮🇪',
    clubs: 'Ulster / Ospreys / Ireland / Lions',
    stat: '69 caps for Ireland. 2 Lions tours. Now a TV presenter — swapped the try line for the front of camera',
  },

  // ── SCOTLAND ──────────────────────────────────────────────────────────────
  {
    id: 'craig-chalmers',
    slug: 'craig-chalmers',
    name: 'Craig Chalmers',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Edinburgh / Glasgow / Harlequins / Scotland / Lions',
    stat: '60 caps for Scotland. Kicked the winning drop goal in the famous 1990 Grand Slam decider against England',
  },
  {
    id: 'duncan-taylor',
    slug: 'duncan-taylor',
    name: 'Duncan Taylor',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Saracens / Scotland',
    stat: '25 caps for Scotland. Won multiple Premiership and European titles with Saracens',
  },
  {
    id: 'hugo-southwell',
    slug: 'hugo-southwell',
    name: 'Hugo Southwell',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Stade Français, Wasps & Scotland',
    stat: 'Before earning 59 rugby caps for Scotland, Hugo came through the youth ranks at Sussex Cricket Club and played Grade A cricket as an all-rounder',
  },
  {
    id: 'jim-hamilton',
    slug: 'jim-hamilton',
    name: 'Jim Hamilton',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Leicester, Edinburgh, Saracens & Scotland',
    stat: 'Standing 6 ft 8 in, "Big Jim" officially became the 1,000th player to wear the thistle for Scotland before transitioning into one of the most hilariously candid media hosts in modern rugby',
  },
  {
    id: 'kelly-brown',
    slug: 'kelly-brown',
    name: 'Kelly Brown',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Glasgow / Saracens / Scotland',
    stat: '64 caps for Scotland. Captained his country and won the Premiership with Saracens',
  },
  {
    id: 'ollie-atkins',
    slug: 'ollie-atkins',
    name: 'Ollie Atkins',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Edinburgh / Exeter',
    stat: 'Part of the Exeter squad that climbed from the Championship to European champions',
  },
  {
    id: 'rory-lawson',
    slug: 'rory-lawson',
    name: 'Rory Lawson',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Edinburgh / Gloucester / Scotland',
    stat: '31 caps for Scotland. Can turn any bar into a party with Piano Man and a harmonica',
  },
  {
    id: 'ryan-wilson',
    slug: 'ryan-wilson',
    name: 'Ryan Wilson',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Glasgow / Scotland',
    stat: '50 caps for Scotland. Since retiring he\'s started Scrum2Scratch, a golf series on YouTube',
  },
  {
    id: 'scott-steele',
    slug: 'scott-steele',
    name: 'Scott Steele',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Leicester / London Irish / Harlequins / Glasgow / Scotland',
    stat: 'Played for five professional clubs across England and Scotland — the well-travelled scrum-half',
  },
  {
    id: 'sean-lamont',
    slug: 'sean-lamont',
    name: 'Sean Lamont',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Glasgow / Northampton / Scotland',
    stat: '105 caps for Scotland. Most capped Scottish back of all time — and posed for the famous Dieux du Stade calendar in 2007',
  },
  {
    id: 'sean-maitland',
    slug: 'sean-maitland',
    name: 'Sean Maitland',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Glasgow / Saracens / Scotland / Lions',
    stat: '50+ caps for Scotland. New Zealand-born. Lions tourist 2013. Won the Premiership with Saracens',
  },
  {
    id: 'tommy-seymour',
    slug: 'tommy-seymour',
    name: 'Tommy Seymour',
    country: 'Scotland',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    clubs: 'Glasgow / Scotland / Lions',
    stat: '55 caps for Scotland. American-born, Ulster-raised, Glasgow legend — scored tries for fun in Pro14',
  },

  // ── SOUTH AFRICA ──────────────────────────────────────────────────────────
  {
    id: 'schalk-brits',
    slug: 'schalk-brits',
    name: 'Schalk Brits',
    country: 'South Africa',
    flag: '🇿🇦',
    clubs: 'Saracens / South Africa',
    stat: '10 caps for South Africa. Came out of retirement to play in the 2019 World Cup — and won it',
  },

  // ── AUSTRALIA ─────────────────────────────────────────────────────────────
  {
    id: 'morgan-turunuri',
    slug: 'morgan-turunuri',
    name: 'Morgan Turunuri',
    country: 'Australia',
    flag: '🇦🇺',
    clubs: 'Randwick, Waratahs, Queensland Reds, Stade Français, US Dax & Australia',
    stat: 'In 2003, he scored a record six tries in a single club game for Randwick against Warringah, which immediately catapulted him into both the Waratahs and Wallabies squads that very same year!',
  },
  {
    id: 'tim-horan',
    slug: 'tim-horan',
    name: 'Tim Horan',
    country: 'Australia',
    flag: '🇦🇺',
    clubs: 'Souths (Brisbane), Queensland Reds, Saracens & Australia',
    stat: 'Voted Player of the Tournament at the 1999 Rugby World Cup, this two-time World Cup winner (1991 & 1999) famously met his legendary Wallabies midfield partner, Jason Little, when they were 13 years old rooming together',
  },
  {
    id: 'henry-speight',
    slug: 'henry-speight',
    name: 'Henry Speight',
    country: 'Australia',
    flag: '🇦🇺',
    clubs: 'Brumbies / Ulster / Queensland Reds / Biarritz / Australia',
    stat: '9 caps for Australia. Fijian-born speedster — could outrun most players from a standing start',
  },
  {
    id: 'petrus-du-plessis',
    slug: 'petrus-du-plessis',
    name: 'Petrus (Parra) du Plessis',
    country: 'Australia',
    flag: '🇦🇺',
    clubs: 'Saracens / London Irish / Australia coaching',
    stat: 'South African-born prop who became a Saracens cult hero — known for his scrummaging masterclasses',
  },

  // ── USA ───────────────────────────────────────────────────────────────────
  {
    id: 'sean-mcnulty',
    slug: 'sean-mcnulty',
    name: 'Sean McNulty',
    country: 'USA',
    flag: '🇺🇸',
    clubs: 'LA Gilitinis / Miami Sharks / USA Eagles',
    stat: 'USA Eagles international. Helped grow the game in Major League Rugby across America',
  },

  // ── SPECIAL ROLES ─────────────────────────────────────────────────────────
  {
    id: 'christophe-ridley',
    slug: 'christophe-ridley',
    name: 'Christophe Ridley',
    country: 'Referee',
    flag: '🏉',
    clubs: 'IRB Referee',
    homeLocation: 'Cheltenham',
    stat: 'International referee — keeps the legends in line (or tries to)',
  },
  {
    id: 'rob-shotton',
    slug: 'rob-shotton',
    name: 'Rob Shotton',
    country: 'LooseHeadz',
    flag: '💚',
    clubs: 'Co-Founder LooseHeadz',
    homeLocation: 'London',
    stat: 'Co-founded LooseHeadz to tackle mental health in rugby — changing the conversation one scrum cap at a time',
  },
  {
    id: 'sarah-webb',
    slug: 'sarah-webb',
    name: 'Sarah Webb',
    country: 'Wooden Spoon',
    flag: '🥄',
    clubs: 'CEO Wooden Spoon',
    homeLocation: 'Southampton',
    stat: 'CEO of Wooden Spoon — the rugby charity that has raised over £30m for disadvantaged children',
  },
]

export const COUNTRY_ORDER = [
  'England',
  'Wales',
  'Ireland',
  'Scotland',
  'South Africa',
  'Australia',
  'USA',
  'Referee',
  'LooseHeadz',
  'Wooden Spoon',
]

export const legendsByCountry = COUNTRY_ORDER.reduce<Record<string, Legend[]>>(
  (acc, country) => {
    const group = legends.filter((l) => l.country === country)
    if (group.length > 0) acc[country] = group
    return acc
  },
  {}
)
